# Generated by Django 4.0.5 on 2022-07-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='description',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='deadline',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='logo',
            field=models.ImageField(null=True, upload_to='%Y-%m-%d', verbose_name='image'),
        ),
    ]
