# Generated by Django 4.0.5 on 2022-07-08 07:01

from django.db import migrations, models
import jsonfield.fields
import scraping.models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0005_remove_vacancy_description_vacancy_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url_data',
            field=jsonfield.fields.JSONField(default=scraping.models.default_urls),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='logo',
            field=models.CharField(max_length=200, null=True, verbose_name='image'),
        ),
    ]
